Algoritmo "Lista 04 - Exercício 39 - Teste de mesa."
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   :
// Autor(a)    : Guilherme Gavassa
// Data atual  : 15/09/2022
Var
   // Seção de Declarações das variáveis...
   senha,usuario:real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
  //a) VERDADEIRO
  //b) FALSO
  //c) VERDADEIRO

Fimalgoritmo
